spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/work_grid
    username: aelkarki
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: on
server:
  port: 8080
